import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Local test artifacts:
    "coverage/**",
    "test-results/**",
    "playwright-report/**",
    // Binary traces/screenshots generated by e2e + visual tests:
    "**/*.png",
    "**/*.jpg",
    "**/*.jpeg",
    "**/*.webp",
    "**/*.zip",
    "**/*.trace",
    "**/*.har",
  ]),
]);

export default eslintConfig;
