import type {
  BadgeProgress,
  CBTIProfile,
  Company,
  CompanyVibeTag,
  CurrentUser,
  DailyTask,
  MyReviewEntry,
  RecommendedCompanyItem,
  Review,
  ReviewDiscussionItem,
  ReplyItem,
} from "@/lib/types"

type ReviewSeed = Omit<
  Review,
  "shortComment" | "jobCategory" | "employmentStatus" | "trustLevel" | "commentCount" | "city" | "comments"
> &
  Partial<
    Pick<
      Review,
      "shortComment" | "jobCategory" | "employmentStatus" | "trustLevel" | "commentCount" | "city" | "comments"
    >
  >

const reviews: ReviewSeed[] = [
  {
    id: "review-1",
    companyId: "northstar-tech",
    role: "前端工程师",
    relation: "离职员工",
    tenure: "2 年 4 个月",
    score: 7.8,
    title: "节奏快，但工程氛围和同事协作比较稳定",
    content:
      "先说结论：如果你想找一个完全稳定、需求几个月不变的环境，这里可能不合适；如果你能接受业务目标变化，同时希望工程团队本身比较讲方法，这里可以重点看看。\n\n我在的时候需求优先级确实调过几次，有时候一周内会从增长转到留存，再转到企业客户交付。但研发内部不是纯靠拍脑袋推进，Code Review 比较认真，线上问题也会复盘。直属负责人愿意帮团队挡掉一部分临时需求，这点挺重要。\n\n建议面试时直接问：试用期目标怎么定、需求变化时绩效怎么判断、技术债有没有固定窗口。问清楚这些，比只问加不加班更有用。",
    tags: ["研发流程清晰", "节奏偏快", "管理透明"],
    helpful: 428,
    createdAt: "2026-05-12",
    verifiedHint: "已完成匿名凭证校验",
    verified: true,
  },
  {
    id: "review-2",
    companyId: "northstar-tech",
    role: "产品经理",
    relation: "在职员工",
    tenure: "11 个月",
    score: 6.6,
    title: "目标感强，跨部门沟通成本需要提前评估",
    content:
      "产品岗体验比较两面。一方面业务目标很明确，老板和业务负责人都知道自己要什么，不会让你长期做没有人看的项目；另一方面，目标变化后跨部门同步成本比较高。\n\n我遇到过一个版本，销售、运营、客户成功对优先级理解不一致，最后产品要花很多时间做解释和对齐。团队里优秀的人不少，但如果你不擅长管理预期，会觉得每天都在被拉扯。\n\n入职前建议把汇报线问清楚，也问问绩效是看交付数量、业务指标，还是项目复杂度。这个问题不问，后面会很被动。",
    tags: ["目标压力", "沟通成本", "绩效口径需确认"],
    helpful: 316,
    createdAt: "2026-05-06",
    verifiedHint: "来自在职匿名样本",
  },
  {
    id: "review-3",
    companyId: "northstar-tech",
    role: "算法实习生",
    relation: "实习生",
    tenure: "4 个月",
    score: 8.1,
    title: "实习生能接触真实项目，但导师投入因团队而异",
    content:
      "我实习时不是做边缘需求，确实接触到了线上模型评估和数据清洗流程，也参加过几次评审。对实习生来说，这个项目含金量是够的。\n\n问题在于导师投入不太稳定。导师忙的时候，PR 反馈可能会拖一两天，如果自己不主动同步，很容易卡住。我后来固定每天发一次进度，体验就好很多。\n\n转正这件事不要默认乐观。HR 说有机会，但具体名额和 HC 变化都比较不确定。建议一开始就问清楚转正考核、时间点和历史比例。",
    tags: ["真实项目", "导师差异", "转正不确定"],
    helpful: 189,
    createdAt: "2026-04-27",
    verifiedHint: "匿名身份保护中",
  },
  {
    id: "review-5",
    companyId: "northstar-tech",
    role: "后端工程师",
    relation: "在职员工",
    tenure: "1 年 6 个月",
    score: 7.5,
    title: "技术债有人管，但排期变化要自己留缓冲",
    content:
      "我比较认可的一点是，技术债不是完全没人管。我们组会定期做稳定性治理，也会把一些历史包袱拆成小任务放进迭代里。线上问题复盘不会只找人背锅，更多是看流程哪里可以补。\n\n但排期变化是真的多。业务侧经常根据客户反馈调整优先级，如果你按第一次需求评估把时间卡得很死，后面会非常难受。我现在的做法是所有需求都留一点缓冲，并且把风险写在评审记录里。\n\n适合能主动沟通、愿意把不确定性说在前面的人。不适合特别讨厌变化的人。",
    tags: ["技术治理", "排期变化", "复盘认真"],
    helpful: 276,
    createdAt: "2026-05-18",
    verifiedHint: "来自在职匿名样本",
  },
  {
    id: "review-6",
    companyId: "northstar-tech",
    role: "数据分析师",
    relation: "离职员工",
    tenure: "9 个月",
    score: 6.4,
    title: "数据需求多，口径确认会消耗不少时间",
    content:
      "数据岗不是只做报表，会参与一些业务策略讨论，这点对成长有帮助。但日常最消耗人的地方是口径确认。\n\n同一个指标，增长、销售、客户成功可能会有不同理解。有时候你以为只是取数，最后变成一轮小型需求评审。业务方对响应速度期待很高，数据团队如果不主动管理边界，很容易被碎片需求淹没。\n\n建议候选人问三个问题：有没有统一指标字典、临时取数怎么排优先级、数据问题算业务方还是数据方 owner。答案能反映很多真实协作状态。",
    tags: ["指标口径", "需求边界", "协作成本"],
    helpful: 198,
    createdAt: "2026-05-15",
    verifiedHint: "已完成匿名凭证校验",
  },
  {
    id: "review-7",
    companyId: "northstar-tech",
    role: "设计师",
    relation: "面试者",
    tenure: "面试 3 轮",
    score: 7.0,
    title: "面试关注业务理解，不只是作品集表现",
    content:
      "设计面试不是只看作品集视觉效果，会比较深入地问你为什么这么做、当时业务目标是什么、有没有验证效果。我觉得这点挺好，至少说明团队不是只招执行设计。\n\n流程一共三轮，HR、业务面、交叉面。HR 对岗位情况介绍比较完整，但团队实际节奏要自己追问，比如设计是否参与需求前置讨论、有没有研究资源、设计稿返工主要来自哪里。\n\n最后我没去，主要是个人更想找偏品牌和体验的岗位。这个岗位更偏业务增长和 B 端复杂流程。",
    tags: ["面试体验", "业务理解", "团队节奏需确认"],
    helpful: 121,
    createdAt: "2026-05-10",
    verifiedHint: "面试体验匿名样本",
  },
  {
    id: "review-8",
    companyId: "northstar-tech",
    role: "测试开发",
    relation: "外包 / 派遣",
    tenure: "7 个月",
    score: 5.8,
    title: "外包同学能接触核心流程，但权限和成长路径有限",
    content:
      "外包/派遣同学不是完全边缘，会参与主流程质量保障，也能接触核心系统。但权限、会议参与和成长路径确实和正式员工不同，这个不要靠想象乐观。\n\n我遇到的问题主要是权限申请慢，有些上下游信息需要正式员工转述。团队氛围本身还可以，没有明显区别对待，但制度边界在那里。\n\n如果你以外包身份入职，建议把三件事写清楚：合同主体、加班结算、有没有转岗机会。尤其是转岗，不要只听口头说“以后有机会”。",
    tags: ["外包体验", "权限限制", "合同主体需确认"],
    helpful: 167,
    createdAt: "2026-05-01",
    verifiedHint: "匿名身份保护中",
  },
  {
    id: "review-4",
    companyId: "lighthouse-media",
    role: "内容运营",
    relation: "离职员工",
    tenure: "1 年 2 个月",
    score: 5.9,
    title: "增长目标很明确，但加班节奏波动明显",
    content:
      "项目爆发期会连续加班，淡季会好很多。直属管理比较直接，适合抗压和自驱强的人。建议面试时问清楚排班和调休规则。",
    tags: ["加班波动", "目标压力", "调休需确认"],
    helpful: 241,
    createdAt: "2026-05-03",
    verifiedHint: "已完成匿名凭证校验",
  },
  {
    id: "review-9",
    companyId: "lighthouse-media",
    role: "商业化产品",
    relation: "在职员工",
    tenure: "8 个月",
    score: 6.3,
    title: "成长快是真的，消耗也是真的",
    content:
      "这里适合想快速接触商业化链路的人。你会接触预算、投放、内容策略和销售反馈，不会只待在一个很窄的模块里。\n\n但节奏也是真的快，尤其大促或客户节点前，需求会集中涌入。管理方式比较结果导向，过程解释空间不算大。如果你需要非常稳定的边界，可能会累。\n\n我觉得可以来，但要把自己的预期摆正：它更像训练场，不像舒适区。",
    tags: ["商业化", "成长快", "消耗明显"],
    helpful: 138,
    createdAt: "2026-05-16",
    verifiedHint: "来自在职匿名样本",
  },
  {
    id: "review-10",
    companyId: "lighthouse-media",
    role: "实习运营",
    relation: "实习生",
    tenure: "3 个月",
    score: 6.0,
    title: "实习能学到东西，但别默认转正",
    content:
      "实习工作不是打杂，会接触选题、数据复盘和账号运营。导师愿意讲方法，但团队太忙的时候反馈会比较简短。\n\n最大的问题是转正不确定。我身边有人表现不错但因为 HC 没留下，所以建议实习前就问清楚是否有明确转正名额。\n\n如果只是想积累内容平台经验，我觉得可以；如果目标是稳定转正，需要谨慎。",
    tags: ["实习体验", "转正不确定", "内容运营"],
    helpful: 92,
    createdAt: "2026-05-09",
    verifiedHint: "匿名身份保护中",
  },
  {
    id: "review-11",
    companyId: "river-finance",
    role: "风控算法",
    relation: "在职员工",
    tenure: "1 年 1 个月",
    score: 8.2,
    title: "流程偏重，但确定性不错",
    content:
      "金融科技这类业务天然流程多，很多事情要走合规和审批，所以节奏不会像纯互联网那样快。但好处是目标和边界比较清楚，临时大改相对少。\n\n薪资兑现比较稳定，年终和调薪沟通也比我上一家公司透明。技术上不是最激进，但数据质量和业务场景都还可以。\n\n适合想在稳定业务里做长期积累的人。如果你追求极快迭代和高自由度，可能会觉得流程重。",
    tags: ["薪资稳定", "合规流程", "边界清楚"],
    helpful: 164,
    createdAt: "2026-05-17",
    verifiedHint: "已完成匿名凭证校验",
  },
  {
    id: "review-12",
    companyId: "river-finance",
    role: "后端工程师",
    relation: "面试者",
    tenure: "面试 4 轮",
    score: 7.4,
    title: "面试轮次多，但每轮问题比较对岗",
    content:
      "面试一共四轮，时间线拉得比较长。技术面问得比较细，包括高并发、数据一致性、线上排障，还有一些金融场景下的审计要求。\n\n我不喜欢的是流程等待时间偏长，中间有一周没有反馈。但每轮面试官的问题都比较对岗，没有明显刷题表演。\n\n如果你正在同时推进多个 offer，建议提前和 HR 确认节奏。",
    tags: ["面试轮次多", "问题对岗", "反馈偏慢"],
    helpful: 87,
    createdAt: "2026-05-11",
    verifiedHint: "面试体验匿名样本",
  },
]

const northstarExtraReviews: ReviewSeed[] = [
  {
    id: "review-13",
    companyId: "northstar-tech",
    role: "运维工程师",
    relation: "在职员工",
    tenure: "1 年 2 个月",
    score: 7.1,
    title: "值班机制清晰，但高峰期告警压力明显",
    shortComment: "值班制度透明，业务高峰期压力会明显上来。",
    content:
      "团队的值班轮值规则和告警升级路径是清楚的，文档也比较完整，这点在中型公司里不常见。真正难的是业务高峰期，告警会在短时间集中出现，跨团队定位问题需要较强沟通能力。建议候选人入职前确认值班补贴、调休兑现和夜间故障处理边界。",
    tags: ["流程清晰", "节奏偏快", "值班压力"],
    helpful: 143,
    commentCount: 12,
    createdAt: "2026-05-20",
    verifiedHint: "来自在职匿名样本",
    jobCategory: "运维工程师",
    employmentStatus: "在职员工",
    trustLevel: 3,
    city: "上海",
    comments: [
      { id: "c-13-1", author: "匿名过来人 A", content: "值班补贴这条信息很关键。" },
      { id: "c-13-2", author: "匿名作者", content: "建议面试时直接让 HR 写在 offer 说明里。" },
    ],
  },
  {
    id: "review-14",
    companyId: "northstar-tech",
    role: "测试工程师",
    relation: "离职员工",
    tenure: "1 年",
    score: 6.2,
    title: "质量流程在进步，但需求改动会挤压测试窗口",
    shortComment: "流程在变好，但排期变化会让测试阶段被压缩。",
    content:
      "测试流程上已经有固定冒烟和回归清单，自动化覆盖也在补。问题是业务改动频繁时，联调和回归窗口常被挤压，测试同学容易被动背压。适合愿意主动前置风险的人，不适合只想按固定节奏推进的人。",
    tags: ["流程改进", "排期波动", "风险前置"],
    helpful: 126,
    commentCount: 9,
    createdAt: "2026-05-19",
    verifiedHint: "已完成匿名凭证校验",
    jobCategory: "测试工程师",
    employmentStatus: "离职员工",
    trustLevel: 3,
    city: "上海",
    comments: [{ id: "c-14-1", author: "匿名过来人 B", content: "和我之前体验基本一致。" }],
  },
  {
    id: "review-15",
    companyId: "northstar-tech",
    role: "数据产品经理",
    relation: "在职员工",
    tenure: "10 个月",
    score: 7.3,
    title: "业务目标明确，指标口径需要强推动",
    shortComment: "目标清晰但口径对齐耗时，适合沟通强的人。",
    content:
      "部门对业务目标非常明确，季度重点不会模糊。实际挑战在指标口径，多个团队都在用同一套数据时，解释成本高。你需要主动拉齐术语和看板，不然项目推进会反复。建议面试时问是否有统一指标字典。",
    tags: ["目标明确", "指标口径", "沟通成本"],
    helpful: 118,
    commentCount: 8,
    createdAt: "2026-05-18",
    verifiedHint: "来自在职匿名样本",
    jobCategory: "数据产品经理",
    employmentStatus: "在职员工",
    trustLevel: 2,
    city: "上海",
    comments: [{ id: "c-15-1", author: "匿名作者", content: "没有字典的话重复沟通会很重。" }],
  },
  {
    id: "review-16",
    companyId: "northstar-tech",
    role: "算法工程师",
    relation: "离职员工",
    tenure: "2 年",
    score: 8.0,
    title: "项目难度高，成长快，但评审标准偏严格",
    shortComment: "能快速成长，前提是能适应严格评审。",
    content:
      "模型和业务都不算简单，能接触到完整实验链路和上线流程。团队评审标准偏严格，很多同学前期会感到压力，但长期看能提升工程质量。建议候选人提前确认试用期评估维度，避免只看最终上线结果。",
    tags: ["成长快", "评审严格", "项目复杂"],
    helpful: 207,
    commentCount: 18,
    createdAt: "2026-05-17",
    verifiedHint: "已完成匿名凭证校验",
    jobCategory: "算法工程师",
    employmentStatus: "离职员工",
    trustLevel: 4,
    city: "上海",
    comments: [{ id: "c-16-1", author: "匿名过来人 C", content: "严格评审这点很真实。" }],
  },
  {
    id: "review-17",
    companyId: "northstar-tech",
    role: "前端工程师",
    relation: "在职员工",
    tenure: "1 年 4 个月",
    score: 7.6,
    title: "前端工程规范不错，跨端协作偶尔拉扯",
    shortComment: "前端规范成熟，跨端协作需要主动推动。",
    content:
      "组件库、埋点规范和回归流程都比较健全，新人上手速度快。问题是跨端需求频繁变更时，前后端排期会拉扯，尤其在大版本前夕。建议先问清楚 PRD 冻结机制和紧急需求例外流程。",
    tags: ["工程规范", "跨端协作", "节奏偏快"],
    helpful: 186,
    commentCount: 16,
    createdAt: "2026-05-16",
    verifiedHint: "来自在职匿名样本",
    jobCategory: "前端工程师",
    employmentStatus: "在职员工",
    trustLevel: 3,
    city: "上海",
    comments: [{ id: "c-17-1", author: "匿名作者", content: "冻结机制清楚会省很多扯皮。" }],
  },
  {
    id: "review-18",
    companyId: "northstar-tech",
    role: "后端工程师",
    relation: "离职员工",
    tenure: "1 年 9 个月",
    score: 6.8,
    title: "服务拆分推进中，稳定性治理靠团队自觉",
    shortComment: "架构在进化，稳定性质量受团队执行影响较大。",
    content:
      "公司在做服务拆分，方向是对的，但阶段内会有历史系统和新系统并行的复杂度。有没有稳定性保障，很看团队是否坚持压测、复盘和监控治理。建议面试时确认故障复盘机制是否刚性执行。",
    tags: ["架构演进", "稳定性", "执行差异"],
    helpful: 132,
    commentCount: 11,
    createdAt: "2026-05-14",
    verifiedHint: "匿名身份保护中",
    jobCategory: "后端工程师",
    employmentStatus: "离职员工",
    trustLevel: 3,
    city: "上海",
    comments: [{ id: "c-18-1", author: "匿名过来人 D", content: "并行期确实会比较痛。" }],
  },
  {
    id: "review-19",
    companyId: "northstar-tech",
    role: "产品运营",
    relation: "在职员工",
    tenure: "7 个月",
    score: 6.5,
    title: "运营目标明确，但活动节奏会压缩复盘时间",
    shortComment: "结果导向强，复盘时间容易被下一波活动挤掉。",
    content:
      "增长活动目标定得很清楚，资源协调效率也不低。短板是节奏紧时复盘时间常常被压缩，导致同类问题重复出现。适合抗压和执行力强的人，若偏好慢节奏迭代需要慎重。",
    tags: ["目标压力", "节奏偏快", "复盘不足"],
    helpful: 104,
    commentCount: 7,
    createdAt: "2026-05-13",
    verifiedHint: "来自在职匿名样本",
    jobCategory: "产品运营",
    employmentStatus: "在职员工",
    trustLevel: 2,
    city: "上海",
    comments: [{ id: "c-19-1", author: "匿名过来人 E", content: "复盘窗口这点很关键。" }],
  },
  {
    id: "review-20",
    companyId: "northstar-tech",
    role: "HRBP",
    relation: "离职员工",
    tenure: "1 年 3 个月",
    score: 6.9,
    title: "业务伙伴参与度高，组织变化同步压力大",
    shortComment: "HRBP 接触业务深，但组织变动期沟通压力不小。",
    content:
      "在这边做 HRBP 能参与到比较前线的业务决策，学习价值不错。组织变化阶段的沟通压力会很明显，尤其涉及绩效口径和岗位调整时。建议候选人明确汇报线和组织决策节奏。",
    tags: ["组织变化", "沟通压力", "参与业务"],
    helpful: 96,
    commentCount: 6,
    createdAt: "2026-05-12",
    verifiedHint: "匿名身份保护中",
    jobCategory: "HRBP",
    employmentStatus: "离职员工",
    trustLevel: 2,
    city: "上海",
    comments: [{ id: "c-20-1", author: "匿名作者", content: "沟通成本会被低估。" }],
  },
  {
    id: "review-21",
    companyId: "northstar-tech",
    role: "算法工程师",
    relation: "在职员工",
    tenure: "1 年 5 个月",
    score: 8.3,
    title: "模型实践机会多，但业务迭代会拉高试错成本",
    shortComment: "实践机会多，代价是迭代快时试错成本变高。",
    content:
      "能做真实线上模型，数据量和业务反馈都比较有价值。业务迭代快的时候，实验周期容易被压缩，部分方案验证不够完整。整体仍适合想做业务模型落地的人，但要接受节奏变化。",
    tags: ["成长快", "真实业务", "迭代快"],
    helpful: 173,
    commentCount: 14,
    createdAt: "2026-05-11",
    verifiedHint: "来自在职匿名样本",
    jobCategory: "算法工程师",
    employmentStatus: "在职员工",
    trustLevel: 4,
    city: "上海",
    comments: [{ id: "c-21-1", author: "匿名过来人 F", content: "落地机会多这点认可。" }],
  },
  {
    id: "review-22",
    companyId: "northstar-tech",
    role: "设计师",
    relation: "在职员工",
    tenure: "1 年",
    score: 7.2,
    title: "设计参与业务前置，返工率看项目组管理",
    shortComment: "能参与前置讨论，但返工率受项目管理差异影响。",
    content:
      "不少项目会让设计提前进入讨论，而不是最后做视觉交付，这点对成长有帮助。返工率主要取决于项目管理质量，需求边界不稳时会比较折腾。建议面试时问设计在需求评审中的决策权。",
    tags: ["业务前置", "返工风险", "成长机会"],
    helpful: 115,
    commentCount: 10,
    createdAt: "2026-05-10",
    verifiedHint: "已完成匿名凭证校验",
    jobCategory: "设计师",
    employmentStatus: "在职员工",
    trustLevel: 3,
    city: "上海",
    comments: [{ id: "c-22-1", author: "匿名过来人 G", content: "评审中的话语权确实关键。" }],
  },
  {
    id: "review-23",
    companyId: "northstar-tech",
    role: "数据工程师",
    relation: "离职员工",
    tenure: "1 年 8 个月",
    score: 6.7,
    title: "数据基建投入在提升，但临时需求仍多",
    shortComment: "基建在补齐，临时取数和临时口径仍然偏多。",
    content:
      "数据仓库规范和监控做得比两年前好很多，团队也在补数据质量治理。痛点在临时需求，业务方常会在关键节点追加临时取数。适合能管理优先级的人，不适合特别排斥临时变化的人。",
    tags: ["数据基建", "临时需求", "优先级管理"],
    helpful: 109,
    commentCount: 9,
    createdAt: "2026-05-09",
    verifiedHint: "匿名身份保护中",
    jobCategory: "数据工程师",
    employmentStatus: "离职员工",
    trustLevel: 3,
    city: "上海",
    comments: [{ id: "c-23-1", author: "匿名作者", content: "关键节点临时需求会堆在一起。" }],
  },
  {
    id: "review-24",
    companyId: "northstar-tech",
    role: "销售运营",
    relation: "在职员工",
    tenure: "6 个月",
    score: 6.1,
    title: "销售目标压力高，流程协作比想象中规范",
    shortComment: "压力不小，但流程比传统销售团队更规范。",
    content:
      "目标压力确实高，尤其季度末。优点是协作流程比我之前公司规范，数据和复盘机制都更完整。若你希望高强度成长可以考虑；若更看重稳定作息，需要提前确认节奏。",
    tags: ["目标压力", "流程规范", "节奏快"],
    helpful: 93,
    commentCount: 6,
    createdAt: "2026-05-08",
    verifiedHint: "来自在职匿名样本",
    jobCategory: "销售运营",
    employmentStatus: "在职员工",
    trustLevel: 2,
    city: "上海",
    comments: [{ id: "c-24-1", author: "匿名过来人 H", content: "季度末强度确实会拉满。" }],
  },
  {
    id: "review-25",
    companyId: "northstar-tech",
    role: "法务",
    relation: "在职员工",
    tenure: "1 年",
    score: 7.0,
    title: "法务参与前置较多，跨部门解释成本高",
    shortComment: "前置介入能控风险，但解释和推进成本不低。",
    content:
      "法务在这边不是最后盖章，很多项目会在前期就介入，这对风险控制是好事。挑战在于跨部门理解差异，推进时需要大量解释。适合愿意深入业务的人，不太适合只做流程审查的人。",
    tags: ["风险前置", "跨部门协作", "解释成本"],
    helpful: 88,
    commentCount: 5,
    createdAt: "2026-05-07",
    verifiedHint: "来自在职匿名样本",
    jobCategory: "法务",
    employmentStatus: "在职员工",
    trustLevel: 2,
    city: "上海",
    comments: [{ id: "c-25-1", author: "匿名作者", content: "前置介入确实能少很多返工。" }],
  },
  {
    id: "review-26",
    companyId: "northstar-tech",
    role: "财务BP",
    relation: "离职员工",
    tenure: "1 年 4 个月",
    score: 6.6,
    title: "预算管理流程完整，变更周期内沟通频繁",
    shortComment: "预算机制完整，但业务变更会带来高频沟通。",
    content:
      "预算制定和复盘机制比较完整，口径比我以前公司清晰。业务方向变更周期里，预算调整会很频繁，沟通消耗较大。候选人可以重点问预算变更的审批层级和响应时间。",
    tags: ["预算管理", "沟通成本", "流程清晰"],
    helpful: 79,
    commentCount: 4,
    createdAt: "2026-05-06",
    verifiedHint: "匿名身份保护中",
    jobCategory: "财务BP",
    employmentStatus: "离职员工",
    trustLevel: 2,
    city: "上海",
    comments: [{ id: "c-26-1", author: "匿名过来人 I", content: "审批层级会直接影响效率。" }],
  },
  {
    id: "review-27",
    companyId: "northstar-tech",
    role: "算法实习生",
    relation: "实习生",
    tenure: "5 个月",
    score: 7.9,
    title: "实习任务真实，反馈节奏看导师安排",
    shortComment: "任务真实，有成长，但反馈节奏依赖导师时间。",
    content:
      "实习不是做边缘工作，能参与模型评估和数据处理。优点是项目真实，缺点是反馈节奏比较看导师是否有空。建议实习初期主动约固定同步，不然容易因等待反馈拖慢进度。",
    tags: ["真实项目", "导师差异", "成长快"],
    helpful: 141,
    commentCount: 13,
    createdAt: "2026-05-05",
    verifiedHint: "匿名身份保护中",
    jobCategory: "算法实习生",
    employmentStatus: "实习生",
    trustLevel: 2,
    city: "上海",
    comments: [{ id: "c-27-1", author: "匿名作者", content: "固定同步对实习生很关键。" }],
  },
  {
    id: "review-28",
    companyId: "northstar-tech",
    role: "采购",
    relation: "在职员工",
    tenure: "9 个月",
    score: 6.4,
    title: "供应商管理细致，但紧急采购周期紧张",
    shortComment: "流程完整，紧急场景下节奏会非常快。",
    content:
      "供应商准入和管理流程比较细，风险控制意识也不错。难点在紧急采购场景，跨团队响应时间短，信息同步压力高。适合执行力和协调能力强的人。",
    tags: ["流程细致", "协同压力", "节奏偏快"],
    helpful: 72,
    commentCount: 4,
    createdAt: "2026-05-04",
    verifiedHint: "来自在职匿名样本",
    jobCategory: "采购",
    employmentStatus: "在职员工",
    trustLevel: 2,
    city: "上海",
    comments: [{ id: "c-28-1", author: "匿名过来人 J", content: "紧急场景确实考验协同。" }],
  },
  {
    id: "review-29",
    companyId: "northstar-tech",
    role: "安全工程师",
    relation: "在职员工",
    tenure: "1 年 1 个月",
    score: 7.4,
    title: "安全评审逐步前置，业务接受度在提升",
    shortComment: "安全治理在向前置走，业务配合度逐渐改善。",
    content:
      "最近一年安全评审明显前置，项目上线前的风险梳理更系统。业务侧对安全要求的接受度在提升，但紧急发布时仍会有冲突。整体趋势是变好，适合希望做长期治理的人。",
    tags: ["安全治理", "流程前置", "长期价值"],
    helpful: 111,
    commentCount: 7,
    createdAt: "2026-05-03",
    verifiedHint: "已完成匿名凭证校验",
    jobCategory: "安全工程师",
    employmentStatus: "在职员工",
    trustLevel: 3,
    city: "上海",
    comments: [{ id: "c-29-1", author: "匿名作者", content: "发布窗口冲突还需要管理机制。" }],
  },
  {
    id: "review-30",
    companyId: "northstar-tech",
    role: "解决方案顾问",
    relation: "离职员工",
    tenure: "1 年 7 个月",
    score: 6.3,
    title: "客户场景多样，交付节奏和范围管理是难点",
    shortComment: "客户场景丰富，但范围管理做不好会很累。",
    content:
      "能接触到不同行业客户场景，经验积累很快。最难的是范围管理，客户诉求变化会直接影响交付节奏。建议候选人问清楚变更控制机制和售前售后分工，不然容易长期处在救火状态。",
    tags: ["客户场景", "范围管理", "交付压力"],
    helpful: 97,
    commentCount: 8,
    createdAt: "2026-05-02",
    verifiedHint: "已完成匿名凭证校验",
    jobCategory: "解决方案顾问",
    employmentStatus: "离职员工",
    trustLevel: 3,
    city: "上海",
    comments: [{ id: "c-30-1", author: "匿名过来人 K", content: "变更控制机制非常关键。" }],
  },
]

const reviewQuestionnaireById: Record<string, Review["questionnaire"]> = {
  "review-1": {
    salaryScore: 7,
    growthScore: 8,
    workLifeBalanceScore: 6,
    managementClarityScore: 6,
    collaborationScore: 8,
    stabilityScore: 5,
    integrityScore: 7,
    interviewExperienceScore: 7,
    canteenScore: 8,
    officeEnvironmentScore: 7,
    restroomScore: 6,
    afternoonTeaScore: 5,
    workstationComfortScore: 7,
    commuteConvenienceScore: 8,
    officeEquipmentScore: 7,
    overallOfficeExperienceScore: 7,
    companyPace: "fast",
    managementStyle: "flexible",
    growthExperience: "very_fast",
    collaborationStyle: "cross_team",
    overtimeLevel: "high",
    promiseKeeping: "partially_kept",
  },
  "review-11": {
    salaryScore: 8,
    growthScore: 7,
    workLifeBalanceScore: 7,
    managementClarityScore: 8,
    collaborationScore: 7,
    stabilityScore: 8,
    integrityScore: 8,
    interviewExperienceScore: 7,
    canteenScore: 6,
    officeEnvironmentScore: 8,
    restroomScore: 7,
    afternoonTeaScore: 4,
    workstationComfortScore: 8,
    commuteConvenienceScore: 6,
    officeEquipmentScore: 9,
    overallOfficeExperienceScore: 7,
    companyPace: "stable",
    managementStyle: "process_clear",
    growthExperience: "average",
    collaborationStyle: "within_team",
    overtimeLevel: "normal",
    promiseKeeping: "mostly_kept",
  },
}

const allReviews: Review[] = [...reviews, ...northstarExtraReviews].map((review): Review => ({
  ...review,
  shortComment: review.shortComment || review.title,
  jobCategory: review.jobCategory || review.role,
  employmentStatus: review.employmentStatus || review.relation,
  trustLevel: review.trustLevel ?? 3,
  helpful: review.helpful ?? 0,
  commentCount: review.commentCount ?? Math.max(3, Math.floor((review.helpful ?? 0) / 20)),
  city: review.city || "上海",
  comments:
    review.comments && review.comments.length > 0
      ? review.comments
      : [
          {
            id: `${review.id}-q1`,
            author: "匿名过来人 A",
            content: "这个经历和我看到的情况比较接近。",
          },
          {
            id: `${review.id}-q2`,
            author: "匿名作者",
            content: "建议结合具体岗位再判断，差异会比较大。",
          },
        ],
  questionnaire: reviewQuestionnaireById[review.id],
}))

export const reviewDiscussions: ReviewDiscussionItem[] = [
  {
    id: "discussion-1",
    reviewId: "review-1",
    companyId: "northstar-tech",
    type: "question",
    authorRole: "job_seeker",
    authorLabel: "想进大厂",
    content: "想问下这个节奏快是整个公司都这样，还是主要集中在产品和研发？",
    createdAt: "2026-05-20",
    usefulCount: 31,
    status: "visible",
    source: "mock",
    moderationReason: "none",
    tags: ["加班", "团队差异"],
  },
  {
    id: "discussion-2",
    reviewId: "review-1",
    companyId: "northstar-tech",
    type: "supplement",
    authorRole: "former_employee",
    authorLabel: "离职不回头",
    content: "我补充一下，节奏快主要看团队。有些业务线比较稳定，但新项目组变化会明显多一些。",
    createdAt: "2026-05-21",
    usefulCount: 58,
    status: "visible",
    source: "mock",
    moderationReason: "none",
    tags: ["团队差异", "节奏"],
  },
  {
    id: "discussion-3",
    reviewId: "review-1",
    companyId: "northstar-tech",
    type: "question",
    authorRole: "interviewee",
    authorLabel: "面了五轮",
    content: "面试里说试用期目标会单独确认，实际入职后会不会临时变很多？",
    createdAt: "2026-05-22",
    usefulCount: 24,
    status: "visible",
    source: "mock",
    moderationReason: "none",
    tags: ["面试", "试用期"],
  },
  {
    id: "discussion-4",
    reviewId: "review-1",
    companyId: "northstar-tech",
    type: "supplement",
    authorRole: "current_employee",
    authorLabel: "加班加麻了",
    content: "现在研发这边每周会同步一次优先级，临时变化还是有，但比去年少一些。最好问清楚你要去的具体小组。",
    createdAt: "2026-05-23",
    usefulCount: 46,
    status: "visible",
    source: "mock",
    moderationReason: "none",
    tags: ["现在情况", "研发"],
  },
  {
    id: "discussion-5",
    reviewId: "review-1",
    companyId: "northstar-tech",
    type: "question",
    authorRole: "job_seeker",
    authorLabel: "匿名求职者",
    content: "想了解薪资兑现情况，绩效奖金会不会因为需求变化导致评价口径变掉？",
    createdAt: "2026-05-24",
    usefulCount: 19,
    status: "visible",
    source: "mock",
    moderationReason: "none",
    tags: ["薪资", "绩效"],
  },
  {
    id: "discussion-6",
    reviewId: "review-1",
    companyId: "northstar-tech",
    type: "supplement",
    authorRole: "former_employee",
    authorLabel: "离职匿名评价者",
    content: "办公体验我觉得还行，通勤一般，食堂中等。厕所维护比以前好，但高峰期还是会排队。",
    createdAt: "2026-05-25",
    usefulCount: 37,
    status: "visible",
    source: "mock",
    moderationReason: "none",
    tags: ["办公体验", "通勤", "厕所"],
  },
  {
    id: "discussion-7",
    reviewId: "review-1",
    companyId: "northstar-tech",
    type: "question",
    authorRole: "intern",
    authorLabel: "匿名实习生",
    content: "实习生会参与核心项目吗，还是更多做边缘需求和修小问题？",
    createdAt: "2026-05-26",
    usefulCount: 12,
    status: "visible",
    source: "mock",
    moderationReason: "none",
    tags: ["实习", "成长空间"],
  },
  {
    id: "discussion-8",
    reviewId: "review-1",
    companyId: "northstar-tech",
    type: "supplement",
    authorRole: "former_employee",
    authorLabel: "匿名过来人",
    content: "我补充一下，高赞排序应该优先看到这类真实补充：节奏快主要看团队，新项目更忙，老业务线稳定很多。",
    createdAt: "2026-05-18",
    usefulCount: 82,
    replyCount: 3,
    status: "visible",
    source: "mock",
    moderationReason: "none",
    tags: ["高赞补充", "团队差异"],
  },
  {
    id: "discussion-9",
    reviewId: "review-1",
    companyId: "northstar-tech",
    type: "question",
    authorRole: "job_seeker",
    authorLabel: "匿名求职者",
    content: "最近一周还有人面过这个岗位吗，想确认现在面试难度有没有变化？",
    createdAt: "2026-05-27",
    usefulCount: 4,
    status: "visible",
    source: "mock",
    moderationReason: "none",
    tags: ["最新追问", "面试"],
  },
  {
    id: "discussion-10",
    reviewId: "review-1",
    companyId: "northstar-tech",
    type: "supplement",
    authorRole: "anonymous",
    authorLabel: "匿名过来人",
    content: "我刚写了一段补充，内容还在审核中，主要是关于具体团队差异的描述。",
    createdAt: "2026-05-27",
    usefulCount: 0,
    status: "pending_review",
    moderationReason: "none",
    source: "mock",
    createdByCurrentUser: true,
    pendingSync: false,
    tags: ["审核中"],
  },
  {
    id: "discussion-11",
    reviewId: "review-1",
    companyId: "northstar-tech",
    type: "supplement",
    authorRole: "former_employee",
    authorLabel: "匿名过来人",
    content: "通勤这块之前有人直接留了手机号 13812345678 说可以私聊，公开展示时应该打码。",
    maskedContent: "通勤这块之前有人直接留了手机号 [手机号已隐藏] 说可以私聊，公开展示时应该打码。",
    createdAt: "2026-05-26",
    reviewedAt: "2026-05-27",
    usefulCount: 21,
    status: "limited_visible",
    source: "mock",
    moderationReason: "sensitive_info",
    tags: ["打码展示", "通勤"],
  },
  {
    id: "discussion-12",
    reviewId: "review-1",
    companyId: "northstar-tech",
    type: "question",
    authorRole: "job_seeker",
    authorLabel: "匿名求职者",
    content: "这条非作者待审核内容不应该出现在公开列表。",
    createdAt: "2026-05-27",
    usefulCount: 0,
    status: "pending_review",
    source: "mock",
    moderationReason: "none",
    tags: ["非公开"],
  },
  {
    id: "discussion-13",
    reviewId: "review-1",
    companyId: "northstar-tech",
    type: "supplement",
    authorRole: "anonymous",
    authorLabel: "匿名过来人",
    content: "这条补充未通过审核，作者可以看到状态，普通用户不应进入公开排序。",
    createdAt: "2026-05-27",
    usefulCount: 0,
    status: "rejected",
    source: "mock",
    createdByCurrentUser: true,
    pendingSync: false,
    moderationReason: "off_topic",
    tags: ["未通过"],
  },
]

function cbtiTitleFromCode(code: string) {
  if (code.startsWith("RF") && code.includes("G")) return "快节奏成长型"
  if (code.startsWith("SP")) return "稳定流程型"
  if (code.startsWith("SF")) return "稳定协作型"
  return "平衡协作型"
}

export function inferMockCBTI(company: Pick<Company, "dimensions" | "riskTags">): CBTIProfile {
  const growth = company.dimensions.find((d) => d.key === "growth")?.score ?? 6
  const management = company.dimensions.find((d) => d.key === "management")?.score ?? 6
  const workload = company.dimensions.find((d) => d.key === "workload")?.score ?? 6
  const respect = company.dimensions.find((d) => d.key === "respect")?.score ?? 6

  const pace: "R" | "S" = workload < 6.6 || company.riskTags.some((t) => /快|波动|压力/.test(t)) ? "R" : "S"
  const managementAxis: "F" | "P" = management >= 7.2 ? "P" : "F"
  const growthAxis: "G" | "B" = growth >= 7.4 ? "G" : "B"
  const collaborationAxis: "C" | "I" = respect >= 7 ? "C" : "I"
  const code = `${pace}${managementAxis}${growthAxis}${collaborationAxis}`

  return {
    code,
    title: cbtiTitleFromCode(code),
    summary: "基于匿名评价、方向分和结构化问卷信号生成的公司行为画像。",
    axes: {
      pace,
      management: managementAxis,
      growth: growthAxis,
      collaboration: collaborationAxis,
    },
    confidence: 0.71,
    generatedBy: "mock",
    updatedAt: "2026-05-24",
  }
}

const VIBE_TAG_LIBRARY: Record<string, Omit<CompanyVibeTag, "confidence" | "generatedBy" | "updatedAt">> = {
  hamster_cage: {
    id: "hamster_cage",
    name: "仓鼠笼公司",
    shortName: "仓鼠笼",
    summary: "公司不大、事情很多，节奏密集，容易一直转。",
    signals: ["节奏快", "事务碎", "变化多", "平衡偏低"],
    riskLevel: "high",
    tone: "caution",
  },
  rocket_pad: {
    id: "rocket_pad",
    name: "火箭发射台公司",
    shortName: "火箭发射台",
    summary: "节奏和压力都高，但成长与项目密度也高。",
    signals: ["成长高", "项目密度高", "节奏快", "加班偏高"],
    riskLevel: "medium",
    tone: "neutral",
  },
  warm_tank: {
    id: "warm_tank",
    name: "温水鱼缸公司",
    shortName: "温水鱼缸",
    summary: "环境稳定、压力不大，但成长速度可能偏慢。",
    signals: ["稳定高", "平衡较好", "成长一般", "加班较少"],
    riskLevel: "low",
    tone: "neutral",
  },
  maze_factory: {
    id: "maze_factory",
    name: "迷宫工厂公司",
    shortName: "迷宫工厂",
    summary: "流程和层级偏多，推进事情常常要绕路。",
    signals: ["流程重", "审批多", "协作成本高", "决策慢"],
    riskLevel: "high",
    tone: "caution",
  },
  screw_role: {
    id: "screw_role",
    name: "螺丝钉公司",
    shortName: "螺丝钉",
    summary: "分工细且稳定，但个人发挥空间相对有限。",
    signals: ["分工细", "流程明确", "职责窄", "稳定"],
    riskLevel: "medium",
    tone: "neutral",
  },
  honey_pot: {
    id: "honey_pot",
    name: "蜜罐公司",
    shortName: "蜜罐",
    summary: "福利和环境不错，挑战强度可能没那么高。",
    signals: ["食堂高", "环境高", "下午茶高", "平衡较好"],
    riskLevel: "low",
    tone: "positive",
  },
  spring_bed: {
    id: "spring_bed",
    name: "弹簧床公司",
    shortName: "弹簧床",
    summary: "压力存在，但团队有缓冲，整体弹性较好。",
    signals: ["节奏中等", "协作较好", "管理灵活", "平衡中上"],
    riskLevel: "low",
    tone: "positive",
  },
  toll_station: {
    id: "toll_station",
    name: "高速收费站公司",
    shortName: "高速收费站",
    summary: "流程清楚、节奏固定，但每一步都要过关。",
    signals: ["流程清楚", "审批偏多", "稳定高", "灵活性低"],
    riskLevel: "medium",
    tone: "caution",
  },
}

function buildVibeTag(tagId: keyof typeof VIBE_TAG_LIBRARY, confidence: number): CompanyVibeTag {
  const base = VIBE_TAG_LIBRARY[tagId]
  return {
    ...base,
    confidence,
    generatedBy: "mock",
    updatedAt: "2026-05-25",
  }
}

export function inferCompanyVibeTag(company: Pick<Company, "size" | "dimensions" | "riskTags">, reviewList: Review[]): CompanyVibeTag {
  const growth = company.dimensions.find((d) => d.key === "growth")?.score ?? 6
  const management = company.dimensions.find((d) => d.key === "management")?.score ?? 6
  const workload = company.dimensions.find((d) => d.key === "workload")?.score ?? 6
  const paceFast = reviewList.some((review) => /忙|杂|变化快|节奏快|事情多/.test(review.content + review.title))
  const smallSize = /100-|300-|500-/.test(company.size)
  const hasProcessHeavy = company.riskTags.some((tag) => /流程|审批/.test(tag)) || management >= 7.6

  if (smallSize && workload <= 6.2 && paceFast) return buildVibeTag("hamster_cage", 0.79)
  if (growth >= 8 && workload <= 6.4) return buildVibeTag("rocket_pad", 0.76)
  if (growth <= 7 && workload >= 7.1) return buildVibeTag("warm_tank", 0.73)
  if (hasProcessHeavy && growth < 7.8) return buildVibeTag("maze_factory", 0.74)
  if (management >= 7.8 && growth <= 7.4) return buildVibeTag("toll_station", 0.71)
  return buildVibeTag("spring_bed", 0.68)
}

export function calculateOfficeExperienceScore(questionnaire?: Review["questionnaire"]) {
  if (!questionnaire) return undefined
  if (questionnaire.overallOfficeExperienceScore) return questionnaire.overallOfficeExperienceScore
  const values = [
    questionnaire.canteenScore,
    questionnaire.officeEnvironmentScore,
    questionnaire.restroomScore,
    questionnaire.afternoonTeaScore,
    questionnaire.workstationComfortScore,
    questionnaire.commuteConvenienceScore,
    questionnaire.officeEquipmentScore,
  ].filter((score): score is number => typeof score === "number")
  if (!values.length) return undefined
  return Number((values.reduce((acc, current) => acc + current, 0) / values.length).toFixed(1))
}

export const companies: Company[] = [
  {
    id: "northstar-tech",
    claimedStatus: "unclaimed",
    verifiedIdentityCount: 186,
    source: "mock",
    pendingReview: false,
    reviewStatus: "reviewable",
    name: "北辰智造科技",
    shortName: "北辰智造",
    industry: "AI 工具 / 企业协作",
    city: "上海",
    size: "500-1000 人",
    stage: "C 轮",
    directionScore: 7.4,
    recommendationRate: 72,
    reviewCount: 1304,
    salaryRange: "25k-42k x 14",
    riskLevel: "中",
    riskTags: ["业务变化快", "绩效口径需确认", "跨部门沟通成本"],
    trustLevel: "可信等级 A-",
    highlights: ["工程流程较成熟", "核心团队稳定", "薪资竞争力中上"],
    compassBriefs: [
      {
        id: "brief-1",
        text: "适合能接受业务变化、希望参与复杂工程治理的人，入职前重点确认绩效口径。",
        score: 7.8,
        helpful: 512,
        source: "离职员工",
      },
      {
        id: "brief-2",
        text: "研发流程比同阶段公司稳定，但跨部门目标变化会影响个人节奏。",
        score: 7.2,
        helpful: 369,
        source: "在职员工",
      },
      {
        id: "brief-3",
        text: "实习项目含金量不错，转正预期要提前问清楚，不要只看口头承诺。",
        score: 8.1,
        helpful: 204,
        source: "实习生",
      },
    ],
    lowScoreReasons: [
      {
        label: "业务方向调整频繁",
        count: 184,
        summary: "低分样本主要集中在需求优先级变化和排期反复，影响个人节奏判断。",
      },
      {
        label: "绩效口径需要确认",
        count: 143,
        summary: "部分岗位反馈试用期目标和正式绩效指标衔接不够清晰。",
      },
      {
        label: "跨部门沟通成本",
        count: 127,
        summary: "产品、运营、研发之间的目标切换会带来额外同步成本。",
      },
    ],
    recommendationReasons: [
      {
        label: "工程流程较成熟",
        count: 296,
        summary: "高分样本认可 Code Review、技术补债和线上质量意识。",
      },
      {
        label: "核心团队稳定",
        count: 221,
        summary: "多数正向评价提到直属团队协作稳定，负责人愿意保护研发节奏。",
      },
      {
        label: "项目复杂度高",
        count: 198,
        summary: "适合希望在 AI 工具和企业协作场景快速积累经验的人。",
      },
    ],
    dimensions: [
      { key: "growth", label: "成长方向", score: 8.1, description: "项目复杂度、学习密度与导师投入" },
      { key: "management", label: "管理清晰度", score: 6.8, description: "目标、汇报线、绩效反馈是否稳定" },
      { key: "workload", label: "工作负荷", score: 6.4, description: "加班波动、排期弹性与恢复时间" },
      { key: "pay", label: "薪资兑现", score: 7.7, description: "薪资区间、奖金兑现与调薪透明度" },
      { key: "respect", label: "尊重与边界", score: 7.2, description: "沟通方式、个人边界与匿名安全感" },
    ],
    scoreDistribution: [
      { score: "0-2", count: 42 },
      { score: "2-4", count: 96 },
      { score: "4-6", count: 214 },
      { score: "6-8", count: 602 },
      { score: "8-10", count: 332 },
    ],
    trend: [
      { month: "1月", score: 7.0, reviews: 86 },
      { month: "2月", score: 7.2, reviews: 92 },
      { month: "3月", score: 7.1, reviews: 118 },
      { month: "4月", score: 7.5, reviews: 141 },
      { month: "5月", score: 7.4, reviews: 128 },
    ],
    cbti: {
      code: "RFGC",
      title: "快节奏成长型",
      summary: "评价中频繁出现成长快、节奏快、变化多、跨团队协作等信号。",
      axes: { pace: "R", management: "F", growth: "G", collaboration: "C" },
      confidence: 0.78,
      generatedBy: "mock",
      updatedAt: "2026-05-24",
    },
    vibeTag: buildVibeTag("hamster_cage", 0.79),
    scoreCanteen: 7.8,
    scoreOfficeEnvironment: 7.2,
    scoreRestroom: 6.1,
    scoreAfternoonTea: 5.4,
    scoreWorkstationComfort: 7.0,
    scoreCommuteConvenience: 8.1,
    scoreOfficeEquipment: 7.4,
    scoreOfficeExperience: 7.0,
    reviews: allReviews.filter((review) => review.companyId === "northstar-tech"),
  },
  {
    id: "lighthouse-media",
    claimedStatus: "unclaimed",
    verifiedIdentityCount: 73,
    source: "mock",
    pendingReview: false,
    reviewStatus: "reviewable",
    name: "灯塔互动传媒",
    shortName: "灯塔互动",
    industry: "内容平台 / 增长营销",
    city: "杭州",
    size: "1000-3000 人",
    stage: "已上市",
    directionScore: 6.1,
    recommendationRate: 54,
    reviewCount: 824,
    salaryRange: "16k-28k x 13",
    riskLevel: "高",
    riskTags: ["加班波动", "目标压力", "调休规则需确认"],
    trustLevel: "可信等级 B+",
    highlights: ["增长体系成熟", "项目曝光高", "岗位流动较快"],
    compassBriefs: [
      {
        id: "brief-4",
        text: "增长目标明确，适合抗压强的人；建议面试时确认排班、调休和阶段目标。",
        score: 5.9,
        helpful: 241,
        source: "离职员工",
      },
    ],
    lowScoreReasons: [
      {
        label: "加班节奏波动",
        count: 188,
        summary: "项目爆发期连续加班较多，恢复周期和调休规则需要提前确认。",
      },
      {
        label: "目标压力明显",
        count: 151,
        summary: "低分体验集中在增长目标高、周期短和复盘密度大。",
      },
    ],
    recommendationReasons: [
      {
        label: "项目曝光高",
        count: 133,
        summary: "增长项目接触面广，适合希望快速积累内容平台经验的人。",
      },
      {
        label: "体系成熟",
        count: 119,
        summary: "流程、指标和复盘方法比较完整，新人能快速进入状态。",
      },
    ],
    dimensions: [
      { key: "growth", label: "成长方向", score: 6.9, description: "项目复杂度、学习密度与导师投入" },
      { key: "management", label: "管理清晰度", score: 5.8, description: "目标、汇报线、绩效反馈是否稳定" },
      { key: "workload", label: "工作负荷", score: 4.7, description: "加班波动、排期弹性与恢复时间" },
      { key: "pay", label: "薪资兑现", score: 6.2, description: "薪资区间、奖金兑现与调薪透明度" },
      { key: "respect", label: "尊重与边界", score: 5.9, description: "沟通方式、个人边界与匿名安全感" },
    ],
    scoreDistribution: [
      { score: "0-2", count: 81 },
      { score: "2-4", count: 136 },
      { score: "4-6", count: 277 },
      { score: "6-8", count: 245 },
      { score: "8-10", count: 85 },
    ],
    trend: [
      { month: "1月", score: 6.4, reviews: 64 },
      { month: "2月", score: 6.0, reviews: 81 },
      { month: "3月", score: 6.2, reviews: 77 },
      { month: "4月", score: 5.8, reviews: 103 },
      { month: "5月", score: 6.1, reviews: 92 },
    ],
    cbti: {
      code: "SFGC",
      title: "稳定协作型",
      summary: "评价中更多体现团队氛围、协作和相对稳定节奏。",
      axes: { pace: "S", management: "F", growth: "G", collaboration: "C" },
      confidence: 0.71,
      generatedBy: "mock",
      updatedAt: "2026-05-24",
    },
    vibeTag: buildVibeTag("rocket_pad", 0.74),
    scoreCanteen: 6.9,
    scoreOfficeEnvironment: 7.4,
    scoreRestroom: 6.2,
    scoreAfternoonTea: 6.8,
    scoreWorkstationComfort: 6.5,
    scoreCommuteConvenience: 7.6,
    scoreOfficeEquipment: 6.7,
    scoreOfficeExperience: 6.9,
    reviews: allReviews.filter((review) => review.companyId === "lighthouse-media"),
  },
  {
    id: "river-finance",
    claimedStatus: "unclaimed",
    verifiedIdentityCount: 128,
    source: "mock",
    pendingReview: false,
    reviewStatus: "reviewable",
    name: "江流数科",
    shortName: "江流数科",
    industry: "金融科技",
    city: "深圳",
    size: "300-500 人",
    stage: "B+ 轮",
    directionScore: 7.9,
    recommendationRate: 78,
    reviewCount: 476,
    salaryRange: "28k-50k x 15",
    riskLevel: "低",
    riskTags: ["合规流程重", "面试轮次较多"],
    trustLevel: "可信等级 A",
    highlights: ["薪资兑现稳定", "团队边界感较好", "技术栈较新"],
    compassBriefs: [
      {
        id: "brief-5",
        text: "薪资兑现和团队边界感较稳定，但合规流程比较重，适合偏稳健的候选人。",
        score: 8.0,
        helpful: 176,
        source: "在职员工",
      },
    ],
    lowScoreReasons: [
      {
        label: "合规流程重",
        count: 74,
        summary: "流程节点多，研发和产品推进速度会受到合规节奏影响。",
      },
    ],
    recommendationReasons: [
      {
        label: "薪资兑现稳定",
        count: 156,
        summary: "多数样本认可薪资、奖金和调薪沟通的确定性。",
      },
      {
        label: "边界感较好",
        count: 138,
        summary: "管理方式相对克制，非紧急事项较少侵占休息时间。",
      },
    ],
    dimensions: [
      { key: "growth", label: "成长方向", score: 8.0, description: "项目复杂度、学习密度与导师投入" },
      { key: "management", label: "管理清晰度", score: 7.8, description: "目标、汇报线、绩效反馈是否稳定" },
      { key: "workload", label: "工作负荷", score: 7.1, description: "加班波动、排期弹性与恢复时间" },
      { key: "pay", label: "薪资兑现", score: 8.6, description: "薪资区间、奖金兑现与调薪透明度" },
      { key: "respect", label: "尊重与边界", score: 8.1, description: "沟通方式、个人边界与匿名安全感" },
    ],
    scoreDistribution: [
      { score: "0-2", count: 18 },
      { score: "2-4", count: 44 },
      { score: "4-6", count: 86 },
      { score: "6-8", count: 172 },
      { score: "8-10", count: 156 },
    ],
    trend: [
      { month: "1月", score: 7.5, reviews: 44 },
      { month: "2月", score: 7.7, reviews: 49 },
      { month: "3月", score: 7.8, reviews: 52 },
      { month: "4月", score: 8.0, reviews: 57 },
      { month: "5月", score: 7.9, reviews: 61 },
    ],
    cbti: {
      code: "SPBI",
      title: "稳定流程型",
      summary: "评价中更强调流程、稳定和边界，但成长速度相对一般。",
      axes: { pace: "S", management: "P", growth: "B", collaboration: "I" },
      confidence: 0.69,
      generatedBy: "mock",
      updatedAt: "2026-05-24",
    },
    vibeTag: buildVibeTag("toll_station", 0.73),
    scoreCanteen: 6.1,
    scoreOfficeEnvironment: 8.2,
    scoreRestroom: 7.5,
    scoreAfternoonTea: 4.3,
    scoreWorkstationComfort: 8.1,
    scoreCommuteConvenience: 6.0,
    scoreOfficeEquipment: 8.8,
    scoreOfficeExperience: 7.0,
    reviews: allReviews.filter((review) => review.companyId === "river-finance"),
  },
]

export function getCompany(id: string) {
  return companies.find((company) => company.id === id) ?? companies[0]
}

export function getCompanyReview(companyId: string, reviewId: string) {
  const company = getCompany(companyId)
  return company.reviews.find((review) => review.id === reviewId) ?? null
}

export function getReviewDiscussions(reviewId: string) {
  return reviewDiscussions.filter(
    (item) =>
      item.reviewId === reviewId &&
      (item.status === "visible" ||
        item.status === "limited_visible" ||
        (["local_pending", "pending_review", "hidden", "rejected", "deleted_by_author"].includes(item.status) &&
          item.createdByCurrentUser))
  )
}

// ── Mock threaded replies ──────────────────────────────────────────────────

const mockReplies: Record<string, ReplyItem[]> = {
  "discussion-1": [
    {
      id: "reply-1a",
      discussionId: "discussion-1",
      authorLabel: "咖啡不加糖",
      authorRole: "former_employee",
      content: "主要是产品和研发，运营和市场节奏正常很多。不过就算研发也看组，服务器端比客户端稳定。",
      createdAt: "2026-05-20",
      usefulCount: 45,
      replies: [
        {
          id: "reply-1a1",
          discussionId: "discussion-1",
          authorLabel: "跳槽预备役",
          authorRole: "job_seeker",
          content: "谢谢！那我面的是服务器端，应该还好。",
          createdAt: "2026-05-20",
          usefulCount: 18,
        },
        {
          id: "reply-1a2",
          discussionId: "discussion-1",
          authorLabel: "后端老鸟",
          authorRole: "current_employee",
          content: "确实，我在后端组两年了，整体节奏可控，不过大促前会忙一阵。",
          createdAt: "2026-05-21",
          usefulCount: 23,
        },
      ],
    },
    {
      id: "reply-1b",
      discussionId: "discussion-1",
      authorLabel: "HR小透明",
      authorRole: "anonymous",
      content: "面试时我们会说明具体团队的节奏情况，建议直接问面试官。",
      createdAt: "2026-05-21",
      usefulCount: 12,
    },
  ],
  "discussion-2": [
    {
      id: "reply-2a",
      discussionId: "discussion-2",
      authorLabel: "跳槽预备役",
      authorRole: "job_seeker",
      content: "感谢补充！这个信息很有用，我去打听一下具体是哪个业务线。",
      createdAt: "2026-05-21",
      usefulCount: 28,
    },
    {
      id: "reply-2b",
      discussionId: "discussion-2",
      authorLabel: "实习小能手",
      authorRole: "intern",
      content: "我在的新项目组确实变化多，但mentor会提前同步，还能接受。",
      createdAt: "2026-05-22",
      usefulCount: 15,
    },
  ],
  "discussion-3": [
    {
      id: "reply-3a",
      discussionId: "discussion-3",
      authorLabel: "北漂三年",
      authorRole: "current_employee",
      content: "试用期目标确实会单独签，一般入职第一周就定下来了。后来如果大方向有调整会再做一次review。",
      createdAt: "2026-05-22",
      usefulCount: 34,
    },
  ],
}

export function getDiscussionReplies(discussionId: string): ReplyItem[] {
  return mockReplies[discussionId] ?? []
}

export function createLocalDiscussion(
  input: Pick<ReviewDiscussionItem, "reviewId" | "companyId" | "type" | "authorRole" | "authorLabel" | "content"> & {
    tags?: string[]
  }
): ReviewDiscussionItem {
  return {
    id: `discussion-local-${Date.now()}`,
    reviewId: input.reviewId,
    companyId: input.companyId,
    type: input.type,
    authorRole: input.authorRole,
    authorLabel: input.authorLabel,
    content: input.content.trim(),
    createdAt: "刚刚",
    usefulCount: 0,
    isUsefulByCurrentUser: false,
    status: "local_pending",
    source: "local",
    createdByCurrentUser: true,
    pendingSync: true,
    moderationReason: "none",
    tags: input.tags ?? [],
  }
}

export function searchCompanies(query: string) {
  const normalized = query.trim().toLowerCase()
  if (!normalized) {
    return companies
  }

  return companies.filter((company) =>
    [company.name, company.registeredName, company.shortName, company.englishName, ...(company.alias ?? []), company.industry, company.city]
      .join(" ")
      .toLowerCase()
      .includes(normalized)
  )
}

export const currentUser: CurrentUser = {
  username: "匿名评价者",
  trustLevel: 3,
  directionPoints: 1280,
  nextLevelPoints: 1500,
  streakDays: 7,
  helpedCount: 128,
  badges: ["第一次指路", "连续点灯 7 天", "高赞真实体验", "薪资贡献者", "面试观察员"],
}

/**
 * Reviews authored by the current (mock) user — shown in /me.
 *
 * The prototype reviews don't carry an "isCurrentUser" marker, so we just
 * expose the first few reviews from a couple of companies as the seed.
 * In production this would be `WHERE userId = currentUser.id`.
 */
export const myReviews: MyReviewEntry[] = companies.flatMap((company, companyIndex) =>
  company.reviews
    .filter((_, reviewIndex) => companyIndex < 2 && reviewIndex < 2)
    .map<MyReviewEntry>((review) => ({
      ...review,
      companyId: company.id,
      companyName: company.shortName,
    }))
)

/**
 * Companies the mock user has favorited. Persisted client-side via
 * `favorites-storage.ts` so the heart icon on company pages can also
 * mutate this set.
 */
export const myFavoriteCompanies: { companyId: string; companyName: string; createdAt: string }[] = companies
  .slice(0, 3)
  .map((company, index) => ({
    companyId: company.id,
    companyName: company.shortName,
    createdAt: new Date(Date.now() - (index + 1) * 86_400_000 * 3).toISOString(),
  }))

/** Badge catalog — used by /me to show locked + unlocked progress. */
export const badgeCatalog: BadgeProgress[] = [
  { id: "first-light", name: "第一次点灯", description: "完成首次任意动作", unlocked: true },
  { id: "first-direction", name: "第一次指路", description: "发布第一条匿名评价", unlocked: true },
  {
    id: "streak-7",
    name: "连续点灯 7 天",
    description: "连续 7 天完成任意动作",
    unlocked: true,
    progress: 7,
    target: 7,
  },
  {
    id: "streak-30",
    name: "连续点灯 30 天",
    description: "连续 30 天",
    unlocked: false,
    progress: 7,
    target: 30,
  },
  { id: "helpful-author", name: "高赞真实体验", description: "单条评价有用数 ≥ 50", unlocked: true },
  { id: "salary-contrib", name: "薪资贡献者", description: "贡献 ≥ 3 条薪资区间", unlocked: true },
  { id: "interview-observer", name: "面试观察员", description: "贡献 ≥ 3 条面试体验", unlocked: true },
  {
    id: "risk-spotter",
    name: "避坑达人",
    description: "举报违规内容并被采纳 5 次",
    unlocked: false,
    progress: 1,
    target: 5,
  },
  {
    id: "trusted",
    name: "可信工友",
    description: "指路等级达到 L5",
    unlocked: false,
    progress: 3,
    target: 5,
  },
  { id: "veteran", name: "司南老用户", description: "注册满 1 年", unlocked: false, progress: 0, target: 1 },
]

export const dailyTasks: DailyTask[] = [
  {
    id: "view-company",
    title: "查看 1 家公司",
    rewardPoints: 5,
    progress: 1,
    target: 1,
    completed: true,
    href: "/rankings",
  },
  {
    id: "helpful-review",
    title: "给 1 条评价点有用",
    rewardPoints: 5,
    progress: 0,
    target: 1,
    completed: false,
    href: "/",
    hint: "在任意公司评价下点「有用」",
  },
  {
    id: "write-review",
    title: "匿名评价一家你熟悉的公司",
    rewardPoints: 20,
    progress: 0,
    target: 1,
    completed: false,
    href: "/submit/review",
    hint: "至少 30 字 + 通过匿名安全检查",
  },
  {
    id: "follow-company",
    title: "收藏 1 家你关注的公司",
    rewardPoints: 3,
    progress: 0,
    target: 1,
    completed: false,
    href: "/search",
    hint: "在公司详情页点 ☆ 收藏",
  },
  {
    id: "report-risk",
    title: "查看 1 条风险评价",
    rewardPoints: 3,
    progress: 0,
    target: 1,
    completed: false,
    href: "/community",
  },
]

export const popularSearches = ["北辰智造", "金融科技", "上海 AI", "加班波动", "薪资兑现"]

export const userPreference = {
  targetIndustries: ["机器人", "AI", "自动驾驶", "半导体"],
  targetCities: ["上海", "深圳", "杭州"],
  roles: ["产品经理", "算法工程师", "硬件工程师"],
  experienceLevel: "1-3 年",
  concerns: ["成长空间", "加班强度", "管理风格", "薪资稳定"],
}

export const recommendedCompanyItems: RecommendedCompanyItem[] = [
  {
    id: "rec-1",
    companyId: "northstar-tech",
    companyName: "北辰智造科技",
    industry: "机器人 / AI",
    city: "上海",
    size: "500-1000 人",
    stage: "C 轮",
    directionScore: 7.6,
    reviewCount: 236,
    recommendationRate: 61,
    recommendReason: "为你推荐：机器人方向匹配",
    matchedPreferences: ["机器人", "上海", "成长空间"],
    highlightedMetrics: [
      { label: "成长空间", score: 8.2 },
      { label: "工作生活平衡", score: 6.1 },
      { label: "管理水平", score: 6.5 },
    ],
    vibeTagName: "仓鼠笼公司",
    vibeTagSummary: "公司不大、事情很多，节奏密集。",
    officeExperienceScore: 7.0,
    recentReviewCount: 12,
    recentViewCount: 36,
  },
  {
    id: "rec-2",
    companyId: "northstar-tech",
    companyName: "极光自动驾驶系统",
    industry: "自动驾驶",
    city: "深圳",
    size: "1000-3000 人",
    stage: "B+ 轮",
    directionScore: 7.3,
    reviewCount: 182,
    recommendationRate: 58,
    recommendReason: "与你关注的「成长空间」相关",
    matchedPreferences: ["自动驾驶", "算法工程师", "成长空间"],
    highlightedMetrics: [
      { label: "成长空间", score: 8.0 },
      { label: "薪资福利", score: 7.4 },
      { label: "管理水平", score: 6.2 },
    ],
    vibeTagName: "火箭发射台公司",
    vibeTagSummary: "节奏快、压力高，但成长与项目密度也高。",
    officeExperienceScore: 6.8,
    recentReviewCount: 9,
    recentViewCount: 28,
  },
  {
    id: "rec-3",
    companyId: "river-finance",
    companyName: "江流数科",
    industry: "金融科技",
    city: "深圳",
    size: "300-500 人",
    stage: "B+ 轮",
    directionScore: 7.9,
    reviewCount: 476,
    recommendationRate: 78,
    recommendReason: "薪资稳定与团队边界感匹配",
    matchedPreferences: ["薪资稳定", "深圳", "管理风格"],
    highlightedMetrics: [
      { label: "薪资兑现", score: 8.2 },
      { label: "稳定性", score: 7.9 },
      { label: "管理水平", score: 7.6 },
    ],
    vibeTagName: "螺丝钉公司",
    vibeTagSummary: "边界清楚、兑现稳定，合规流程相对偏重。",
    officeExperienceScore: 7.4,
    recentReviewCount: 7,
    recentViewCount: 31,
  },
  {
    id: "rec-4",
    companyId: "northstar-tech",
    companyName: "云脉新能源智能",
    industry: "新能源",
    city: "杭州",
    size: "1000-3000 人",
    stage: "D 轮",
    directionScore: 6.8,
    reviewCount: 194,
    recommendationRate: 55,
    recommendReason: "为你推荐：杭州岗位 + 管理风格关注命中",
    matchedPreferences: ["杭州", "管理风格", "产品经理"],
    highlightedMetrics: [
      { label: "成长空间", score: 7.3 },
      { label: "工作生活平衡", score: 5.7 },
      { label: "管理水平", score: 6.1 },
    ],
    vibeTagName: "弹簧床公司",
    vibeTagSummary: "压力有，但缓冲也多，整体弹性较好。",
    officeExperienceScore: 6.9,
    recentReviewCount: 10,
    recentViewCount: 27,
  },
  {
    id: "rec-5",
    companyId: "lighthouse-media",
    companyName: "灯塔互动传媒",
    industry: "内容平台 / 增长营销",
    city: "杭州",
    size: "1000-3000 人",
    stage: "已盈利",
    directionScore: 6.1,
    reviewCount: 824,
    recommendationRate: 54,
    recommendReason: "增长岗位与加班强度关注命中",
    matchedPreferences: ["杭州", "加班强度", "产品经理"],
    highlightedMetrics: [
      { label: "项目曝光", score: 7.6 },
      { label: "工作生活平衡", score: 5.2 },
      { label: "管理水平", score: 6.1 },
    ],
    vibeTagName: "火箭发射台公司",
    vibeTagSummary: "项目曝光高、目标明确，爆发期节奏较紧。",
    officeExperienceScore: 6.2,
    recentReviewCount: 14,
    recentViewCount: 42,
  },
  {
    id: "rec-6",
    companyId: "river-finance",
    companyName: "锐构硬件系统",
    industry: "硬件",
    city: "深圳",
    size: "300-500 人",
    stage: "B 轮",
    directionScore: 7.7,
    reviewCount: 122,
    recommendationRate: 64,
    recommendReason: "为你推荐：硬件工程师偏好命中",
    matchedPreferences: ["硬件工程师", "深圳", "管理风格"],
    highlightedMetrics: [
      { label: "成长空间", score: 7.6 },
      { label: "薪资福利", score: 7.8 },
      { label: "管理水平", score: 7.0 },
    ],
    vibeTagName: "螺丝钉公司",
    vibeTagSummary: "分工细且稳定，但个人发挥空间有限。",
    officeExperienceScore: 7.2,
    recentReviewCount: 8,
    recentViewCount: 23,
  },
  {
    id: "rec-7",
    companyId: "lighthouse-media",
    companyName: "澄域互联网平台",
    industry: "互联网平台",
    city: "杭州",
    size: "3000+ 人",
    stage: "已上市",
    directionScore: 6.5,
    reviewCount: 258,
    recommendationRate: 53,
    recommendReason: "杭州互联网方向里近期评价更新频繁",
    matchedPreferences: ["杭州", "产品经理", "管理风格"],
    highlightedMetrics: [
      { label: "成长空间", score: 7.1 },
      { label: "工作生活平衡", score: 5.5 },
      { label: "管理水平", score: 6.2 },
    ],
    vibeTagName: "温水鱼缸公司",
    vibeTagSummary: "环境稳定、压力不大，成长速度可能偏慢。",
    officeExperienceScore: 6.7,
    recentReviewCount: 11,
    recentViewCount: 34,
  },
  {
    id: "rec-8",
    companyId: "northstar-tech",
    companyName: "星轨机器人研究院",
    industry: "机器人",
    city: "上海",
    size: "100-300 人",
    stage: "A+ 轮",
    directionScore: 7.1,
    reviewCount: 96,
    recommendationRate: 59,
    recommendReason: "与你关注的「机器人 / 管理风格」匹配",
    matchedPreferences: ["机器人", "上海", "管理风格"],
    highlightedMetrics: [
      { label: "成长空间", score: 8.3 },
      { label: "工作生活平衡", score: 5.8 },
      { label: "管理水平", score: 6.3 },
    ],
    vibeTagName: "蜜罐公司",
    vibeTagSummary: "福利和环境不错，但挑战强度不一定高。",
    officeExperienceScore: 6.6,
    recentReviewCount: 13,
    recentViewCount: 39,
  },
]
